apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipelines-vote-ui
  name: pipelines-vote-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelines-vote-ui
  template:
    metadata:
      labels:
        app: pipelines-vote-ui
    spec:
      containers:
        - name: pipelines-vote-ui
          image: __IMAGE__
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 9090
            protocol: TCP
          env:
          - name: VOTING_API_SERVICE_HOST
            value: pipelines-vote-api
          - name: VOTING_API_SERVICE_PORT
            value: "9000"
      imagePullSecrets: 
        - name : kaniko-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipelines-vote-ui
  name: pipelines-vote-ui
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: pipelines-vote-ui
---
